# Generated by Django 4.2 on 2024-04-11 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
